### ISSUE TITLE
Error in Chrome

### ISSUE THREAD

**Issue by jrizza** [Polymer/topeka#27]
Hello,
Could you please help me with the following error when clicking in any category?:

```
Exception caught during observer callback: TypeError: Illegal invocation
    at Array.eval [as getValueFrom] (eval at <anonymous> (http://localhost:8000/components/polymer/polymer.js:12:17357), <anonymous>:2:9)
    at valueFn_ (http://localhost:8000/components/polymer/polymer.js:12:276)
    at http://localhost:8000/components/polymer/polymer.js:12:2210
    at http://localhost:8000/components/polymer/polymer.js:12:2165
    at Object.l.getValue (http://localhost:8000/components/polymer/polymer.js:12:4069)
    at Object.d [as getValueFn_] (http://localhost:8000/components/polymer/polymer.js:12:3758)
    at Object.F.observedCallback_ (http://localhost:8000/components/polymer/polymer.js:12:22859)
    at Object.x.report_ (http://localhost:8000/components/polymer/polymer.js:12:18266)
    at Object.S.check_ (http://localhost:8000/components/polymer/polymer.js:12:22604)
    at c (http://localhost:8000/components/polymer/polymer.js:12:12173)
```

This is happening in Chrome (Version 43.0.2357.81 (64-bit)) and not in Safari (Version 8.0.6 (10600.6.3))

**Comment by MrRod** [comment]
I'm getting the same error on Chrome 43 both desktop and mobile. It's basically broken my app! 

Working just fine in Safari too.

**Comment by PoulpiFr** [comment]
I've the same issue with Version 46.0.2490.86 (64-bit).

Categories on which the user is clicking are disappearing when we are going back to the full list of categories. Pretty annoying bug :/
